// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQs1oNgo64a-hWCZpJtbfOxRQr2IljQ_s',
    appId: '1:624091149163:web:705739381795d7c0e0922e',
    messagingSenderId: '624091149163',
    projectId: 'contact-app-fb97b',
    authDomain: 'contact-app-fb97b.firebaseapp.com',
    storageBucket: 'contact-app-fb97b.firebasestorage.app',
    measurementId: 'G-1ZQY72NCN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhVN_DpQCPC7Gu7cPW8ojUoVIRmeiANS8',
    appId: '1:624091149163:android:5d2217bd412e8662e0922e',
    messagingSenderId: '624091149163',
    projectId: 'contact-app-fb97b',
    storageBucket: 'contact-app-fb97b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsScqEBRkZZjFsFiJhqGerEBA-nyxvMAQ',
    appId: '1:624091149163:ios:4e6ba8e33dbe057be0922e',
    messagingSenderId: '624091149163',
    projectId: 'contact-app-fb97b',
    storageBucket: 'contact-app-fb97b.firebasestorage.app',
    iosBundleId: 'com.example.contactApp',
  );
}
